name: Deploy to Railway

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
      working-directory: ./client
    steps:
      - uses: actions/checkout@v3
      - name: Cache node modules
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: npm install and npm run build
        run: |
          npm i
          npm run build:prod
      - name: copy build files
        run: |
          cp client/dist/client/*  server/src/main/resources/static/.

  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./server
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install Railway
        run: npm i -g @railway/cli@2.1.0
      - name: Railway Up
        run: railway up
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
